version: '3'

services:
  redis-auth:
    container_name: redis_auth
    restart: always
    image: 'redis:4-alpine'
    command: redis-server --requirepass mlFV2GMI
    ports:
      - '7379:6379'
    networks:
      default:
        ipv4_address: 172.16.1.1

  postgres-auth:
    container_name: postgres_auth
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '15987'
      PGDATA: /data/postgres_auth
    volumes:
      - postgres_auth:/data/postgres_auth
    ports:
      - "7432:5432"
    networks:
      default:
        ipv4_address: 172.16.1.2

  auth_app:
    build:
      context: auth
    env_file:
      - auth/.env
    command: ["/auth_app/docker/pg_migrate.sh"]
    ports:
      - "8888:8888"
    depends_on:
      - postgres-auth
      - redis-auth
    networks:
      default:
        ipv4_address: 172.16.1.3

  nginx:
    container_name: DOMAIN_NAME-nginx
    hostname: DOMAIN_NAME-nginx
    build: ./volumes/build/nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro #Конфигурация nginx.
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
    restart:
      always
    networks:
      default:
        ipv4_address: 172.16.1.4

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  postgres_auth:
