version: '3'

services:
  redis_auth:
    container_name: redis_auth
    restart: always
    image: 'redis:4-alpine'
    command: redis-server --requirepass mlFV2GMI
    networks:
      default:

  postgres_auth:
    container_name: postgres_auth
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '15987'
      PGDATA: /data/postgres_auth
    volumes:
      - postgres_auth:/data/postgres_auth

  auth_service:
    build:
      context: auth
    env_file:
      - auth/.env
    command: ["/auth_app/docker/pg_migrate.sh"]
    ports:
      - "8888:8080"
    depends_on:
      - postgres_auth
      - redis_auth

  test_service:
    build:
      context: test_service
    env_file:
      - auth/.env

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "443:443"
    links:
      - auth_service
      - test_service
    restart:
      always

volumes:
  postgres_auth:
