version: '3'

services:
  redis-auth:
    container_name: redis_auth
    restart: always
    image: 'redis:4-alpine'
    command: redis-server --requirepass mlFV2GMI
    ports:
      - '9876:9876'
    networks:
      default:

  postgres-auth:
    container_name: postgres_auth
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '15987'
      PGDATA: /data/postgres_auth
    volumes:
      - postgres_auth:/data/postgres_auth
    ports:
      - "1432:5432"
    networks:
      - default

  auth_app:
    build:
      context: auth
    env_file:
      - auth/.env
    command: ["/auth_app/docker/pg_migrate.sh"]
    ports:
      - "8888:8080"
    depends_on:
      - postgres-auth
      - redis-auth
    networks:
      - default

  test_app:
    build:
      context: test_service
    env_file:
      - auth/.env
    ports:
      - "8889:8080"
    networks:
      - default

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - auth_app
      - test_app
    restart:
      always
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_auth:
