version: '3'

services:
  redis:
    restart: always
    image: 'redis:4-alpine'
    command: redis-server --requirepass mlFV2GMI
    ports:
      - '6379:6379'

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '15987'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "7432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
